# Generated by Django 4.0.6 on 2022-07-06 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enter_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_games', models.SmallIntegerField(default=3)),
                ('game_one_p_1', models.SmallIntegerField(default=0)),
                ('game_one_p_2', models.SmallIntegerField(default=0)),
                ('game_two_p_1', models.SmallIntegerField(default=0)),
                ('game_two_p_2', models.SmallIntegerField(default=0)),
                ('game_three_p_1', models.SmallIntegerField(default=0)),
                ('game_three_p_2', models.SmallIntegerField(default=0)),
                ('game_four_p_1', models.SmallIntegerField(default=0)),
                ('game_four_p_2', models.SmallIntegerField(default=0)),
                ('game_five_p_1', models.SmallIntegerField(default=0)),
                ('game_five_p_2', models.SmallIntegerField(default=0)),
                ('game_six_p_1', models.SmallIntegerField(default=0)),
                ('game_six_p_2', models.SmallIntegerField(default=0)),
                ('game_seven_p_1', models.SmallIntegerField(default=0)),
                ('game_seven_p_2', models.SmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('player_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_one_game', to=settings.AUTH_USER_MODEL)),
                ('player_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_two_game', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_game', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Validate_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.CharField(max_length=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.enter_game')),
            ],
        ),
    ]
